#!/usr/bin/php
<?php
require __DIR__ . "/pan/migas/Migas.php";


use Pan\Migas\Migas;


print "Pandemolde :: Migas\n";

if(!isset($argv[1])){
    print "Al parecer no hay parametros ingresados\n";
    print "-- Saludos\n";
    exit(0);
}


$_migas = new Migas($argv);
$_migas->run();

print "\n";
exit(0);



?>